export const GET_POKEMONES = 'GET_POKEMONES';
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
export const CLEAN_POKEMON_DETAIL = 'CLEAN_POKEMON_DETAIL';
export const GET_TYPES = 'GET_TYPES';
export const SELECT_TYPE = 'SELECT_TYPE';
export const FILTER_POKEMON_TYPE = 'FILTER_POKEMON_TYPE';
export const FILTER_POKEMON_ORIGIN = 'FILTER_POKEMON_ORIGIN';